const movies = [
	{title: "Inception", genre: "action", picture: '<img src="https://m.media-amazon.com/pictures/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_UX182_CR0,0,182,268_AL_.jpg" alt="Inception cover">'},
	{title: "Rouge One", genre: "action", picture: '<img src="https://pictures-na.ssl-pictures-amazon.com/pictures/I/91cHWS%2BXaoL._SY606_.jpg" alt="Star Wars cover">'},
	{title: "Mission Impossible", genre: "action", picture: '<img src="https://media.services.cinergy.ch/media/box1600/f1323e57a2c4ea79dde779a89d561f85bfbe6bf5.jpg" alt="Mission Impossible cover">'},
	{title: "The Martian", genre: "action", picture: '<img src="https://upload.wikimedia.org/wikipedia/en/thumb/c/cd/The_Martian_film_poster.jpg/220px-The_Martian_film_poster.jpg" alt="Martian cover">'},
	{title: "Bourne Identity", genre: "action", picture: '<img src="https://upload.wikimedia.org/wikipedia/id/a/ae/BourneIdentityfilm.jpg" alt="Bourne Identity cover">'},
	{title: "Black Panther", genre: "superhero", picture: '<img src="https://i.redd.it/ouoli484y6sz.jpg" alt="Black Panther cover">'},
	{title: "The Avengers", genre: "superhero", picture: '<img src="https://upload.wikimedia.org/wikipedia/en/f/f9/TheAvengers2012Poster.jpg" alt="Avengers cover">'},
	{title: "Er Strange", genre: "superhero", picture: '<img src="https://m.media-amazon.com/pictures/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_.jpg" alt="Dr Strange cover">'},
	{title: "Batman Begins", genre: "superhero", picture: '<img src="https://m.media-amazon.com/pictures/M/MV5BZmUwNGU2ZmItMmRiNC00MjhlLTg5YWUtODMyNzkxODYzMmZlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg" alt="Batman cover">'},
	{title: "Captian America", genre: "superhero", picture: '<img src="https://m.media-amazon.com/pictures/M/MV5BMTYzOTc2NzU3N15BMl5BanBnXkFtZTcwNjY3MDE3NQ@@._V1_.jpg" alt="Captian America cover">'},
	{title: "The Notebook", genre: "romance", picture: '<img src="https://m.media-amazon.com/pictures/M/MV5BMTk3OTM5Njg5M15BMl5BanBnXkFtZTYwMzA0ODI3._V1_UX182_CR0,0,182,268_AL_.jpg" alt="The Notebook cover">'},
	{title: "Titanic", genre: "romance", picture: '<img src="https://upload.wikimedia.org/wikipedia/en/2/22/Titanic_poster.jpg" alt="Titanic cover">'},
	{title: "Casablanca", genre: "romance", picture: '<img src="https://pictures-na.ssl-pictures-amazon.com/pictures/I/71VKH4WGN3L.gif" alt="Casablanca cover">'},
	{title: "You've Got Mail", genre: "romance", picture: '<img src="https://4.bp.blogspot.com/-iV683UDrTDU/WoJUy4igy_I/AAAAAAAAFpQ/Bt7XqX9Wjd8_Olg5NhnzK95p23Qu0MbygCLcBGAs/s1600/youve-got-mail-movie-poster-1998-1020231250.jpg" alt="You\'ve Got Mail cover">'},
	{title: "How to Lose a Guy in Ten Days", genre: "romance", picture: '<img src="https://upload.wikimedia.org/wikipedia/en/thumb/0/07/HowToLoseAGuyimp.jpg/220px-HowToLoseAGuyimp.jpg" alt="How to Lose a Guy in Ten Days cover">'},
	{title: "Psycho", genre: "horror", picture: '<img src="https://m.media-amazon.com/pictures/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg" alt="Psycho cover">'},
	{title: "Texas Chiansaw Masacre", genre: "horror", picture: '<img src="https://upload.wikimedia.org/wikipedia/en/thumb/a/ad/Texas_chainsaw_massacre_the_beginning.jpg/220px-Texas_chainsaw_massacre_the_beginning.jpg" alt="Texas Chian Saw Masacre cover">'},
	{title: "It", genre: "horror", picture: '<img src="https://upload.wikimedia.org/wikipedia/en/5/5a/It_%282017%29_poster.jpg" alt="It cover">'},
	{title: "The Ring", genre: "horror", picture: '<img src="https://upload.wikimedia.org/wikipedia/en/thumb/3/37/Theringpostere.jpg/220px-Theringpostere.jpg" alt="The Ring cover">'},
	{title: "Jaws", genre: "horror", picture: '<img src="https://m.media-amazon.com/pictures/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg" alt="Jaws cover">'},
	{title: "Nacho Libre", genre: "comedy", picture: '<img src="https://upload.wikimedia.org/wikipedia/en/3/35/Nachopost.jpg" alt="Nacho Libre cover">'},
	{title: "Napoleon Dynamite", genre: "comedy", picture: '<img src="https://s3-us-west-2.amazonaws.com/fsl.web/production/media/spotlight/page/poster-650849c3-e0a4-4c85-beaa-3700ba512613.jpg" alt="Napoleon Dynamite cover">'},
	{title: "Ferris Bueller's Day Off", genre: "comedy", picture: '<img src="https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Ferris_Bueller%27s_Day_Off.jpg/220px-Ferris_Bueller%27s_Day_Off.jpg" alt="Ferris Bueller\'s Day Off cover">'},
	{title: "The Princess Bride", genre: "comedy", picture: '<img src="https://imgc.allposterspictures.com/img/print/posters/the-princess-bride-30th-anniversary_a-G-15334565-15312469.jpg" alt="The Princess Bride cover">'},
	{title: "Mean Girls", genre: "comedy", picture: '<img src="https://m.media-amazon.com/pictures/M/MV5BMjE1MDQ4MjI1OV5BMl5BanBnXkFtZTcwNzcwODAzMw@@._V1_.jpg" alt="Mean Girls cover">'},
	{title: "Big Jake", genre: "western", picture: '<img src="https://pictures-na.ssl-pictures-amazon.com/pictures/I/510M8RPGEGL.jpg" alt="Big Jake cover">'},
	{title: "The Magnificent Seven", genre: "western", picture: '<img src="http://www.sonypictures.com/movies/themagnificentseven/assets/pictures/onesheet.jpg" alt="The Magnificent Seven cover">'},
	{title: "True Grit", genre: "western", picture: '<img src="https://resizing.flixster.com/_hCsRR-fL5Z3PXiKuQ9K693JURQ:/206x305/v1.bTsxMTE2OTc5NTtqOzE3OTA0OzEyMDA7ODAwOzEyMDA" alt="True Grit cover">'},
	{title: "Shanghai Noon", genre: "western", picture: '<img src="https://upload.wikimedia.org/wikipedia/en/thumb/e/ee/ShanghaiNoon_Poster.jpg/220px-ShanghaiNoon_Poster.jpg" alt="Shanghai Noon cover">'},
	{title: "Butch Cassidy and the Sundance Kid", genre: "western", picture: '<img src="https://pictures.store.hmv.com/app_/responsive/HMVStore/media/product/101230/01-101230.jpg?w:500" alt="Butch Cassidy and the Sundance Kid cover">'},
	{title: "Star Trek", genre: "scify", picture: '<img src="https://m.media-amazon.com/pictures/M/MV5BNDViYjAyZWUtNGQxMy00MDUyLTlkZTAtOWNkY2M5ZTk5MTE5XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg" alt="Star Trek cover">'},
	{title: "Avatar", genre: "scify", picture: '<img src="https://cdn.europosters.eu/picture/750/posters/avatar-limited-ed-one-sheet-sun-i7182.jpg" alt="Avatar cover">'},
	{title: "Arrival", genre: "scify", picture: '<img src="https://pictures-na.ssl-pictures-amazon.com/pictures/I/91beuN0kgYL._SX425_.jpg" alt="Arrival cover">'},
	{title: "Back to the Future", genre: "scify", picture: '<img src="https://m.media-amazon.com/pictures/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg" alt="Back to the Future cover">'},
	{title: "Interstellar", genre: "scify", picture: '<img src="https://i.pinimg.com/originals/1d/55/0b/1d550b56f35085ed5b26b88d67ed8ddd.png" alt="Interstellar cover">'},
]